// can create a new channel     | create ({})
// can join an existing channel | join ({})
// can post to a channel        | post ({})
// can read the channel         | read ({key})
// can read a channel deep      | find ({key})
// can list channels by account | list ({id})
